language: generic
sudo: required


matrix:
  include:
    - os: linux
      dist: xenial


addons:
  apt:
    update: true
    package:
    - build-essential
    - git
    - curl
    - zip
    - unzip


build:
  script:
    - ./script/ci_build.sh


deploy:
  provider: releases
  api_key: $GITHUB_OAUTH
  skip_cleanup: true
  on:
    tags: true
