language: generic
sudo: required



jobs:
  include:
    - os: linux
      dist: bionic
      node_js:
        - 12.10
    - os: osx
      osx_image: xcode12
      node_js:
        - 12.10

script: ./scripts/ci_build.sh



deploy:
  provider: releases
  name: $TRAVIS_TAG
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: dist_electron/*
  skip_cleanup: true
  draft: true
  on:
    tags: true


